# -*- coding: utf-8 -*-
"""CNNFromScratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179DP-iDW1eQDHdG3TXuC_Twql3EJkKQM

##Name: Chris Mary Benson
##ID: U56085268  
##Email: chris27@bu.edu  

#*This code was run on a Kaggle Notebook (training)
---

**`PART 1: TRAINING CNN FROM SCRATCH`**
"""

# Runtime configuration
FAST_DEV_RUN = False  # True = quick smoke test
SEED = 42

import os

IN_COLAB = False
try:
    import google.colab  # type: ignore
    IN_COLAB = True
except Exception:
    IN_COLAB = False

WORK_ROOT = "/content" if IN_COLAB else os.path.abspath("./temp_student")
os.makedirs(WORK_ROOT, exist_ok=True)

DATA_ROOT = os.path.join(WORK_ROOT, "data")
OOD_DIR = os.path.join(WORK_ROOT, "ood-test-CS541")
SUBMISSION_PATH = os.path.join(WORK_ROOT, "ChrisMaryBenson_part1_1.csv")

print("IN_COLAB:", IN_COLAB)
print("WORK_ROOT:", WORK_ROOT)
print("DATA_ROOT:", DATA_ROOT)
print("OOD_DIR:", OOD_DIR)
print("SUBMISSION_PATH:", SUBMISSION_PATH)

# Install required packages (safe to re-run)
import importlib.util
import subprocess
import sys

required = ["torch", "torchvision", "tqdm", "numpy", "pandas", "matplotlib", "huggingface_hub"]
missing = [p for p in required if importlib.util.find_spec(p) is None]
if missing:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-U", *missing])

print("Environment ready")

import os
import random
from typing import Dict, Optional, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from tqdm import tqdm


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def get_device() -> torch.device:
    if torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


def accuracy_top1(logits: torch.Tensor, targets: torch.Tensor) -> float:
    return (logits.argmax(dim=1) == targets).float().mean().item()


def make_loaders(batch_size: int, num_workers: int) -> Tuple[DataLoader, DataLoader, DataLoader]:
    mean = (0.5071, 0.4867, 0.4408) ### DO NOT CHANGE THIS
    std = (0.2675, 0.2565, 0.2761) ### DO NOT CHANGE THIS

    #Adding more data augmentations to make the model robust
    train_tfms = transforms.Compose([
        transforms.RandomHorizontalFlip(),
        transforms.RandomCrop(32, padding=4),

        #added the additional augmentations below

        transforms.ColorJitter(brightness=0.2, contrast=0.2),
        transforms.RandomGrayscale(p=0.1),
        #transforms.RandAugment(num_ops=2, magnitude=9),
        transforms.AugMix(),
        transforms.ToTensor(),
        transforms.Normalize(mean, std),
        transforms.RandomApply([transforms.GaussianBlur(3, sigma=(0.1, 2.0))], p=0.4),
        transforms.RandomErasing(p=0.25, scale=(0.02, 0.2))
    ])

    eval_tfms = transforms.Compose([transforms.ToTensor(), transforms.Normalize(mean, std)])

    train_full = datasets.CIFAR100(root=DATA_ROOT, train=True, download=True, transform=train_tfms)
    test_ds = datasets.CIFAR100(root=DATA_ROOT, train=False, download=True, transform=eval_tfms)

    n = len(train_full)
    n_train = int(0.8 * n)
    n_val = n - n_train
    g = torch.Generator().manual_seed(SEED)
    train_ds, val_ds = torch.utils.data.random_split(train_full, [n_train, n_val], generator=g)

    if FAST_DEV_RUN:
        train_ds = torch.utils.data.Subset(train_ds, range(min(2048, len(train_ds))))
        val_ds = torch.utils.data.Subset(val_ds, range(min(1024, len(val_ds))))
        test_ds = torch.utils.data.Subset(test_ds, range(min(1024, len(test_ds))))

    if IN_COLAB:
        num_workers = 2

    pin = torch.cuda.is_available()
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=pin)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=pin)
    test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=pin)
    return train_loader, val_loader, test_loader

#Residual Block for CNN
class ResidualBlock(nn.Module):
    def __init__(self, in_ch, out_ch, stride=1, drop_path=0.1):
      #Using drop path which randomly drops the entire residual branch during training for each sample.
      #This acts as regularization by making the network occasionally behave like a
      #shallower model, improving generalization and training stability in deep networks

      #AI assisstance was used here to get an idea about drop path

        super().__init__()
        #First convolution: 3x3 conv
        self.conv1 = nn.Conv2d(in_ch, out_ch, 3, stride=stride, padding=1, bias=False)
        self.bn1   = nn.BatchNorm2d(out_ch)

        #Second convolution with padding
        self.conv2 = nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False)
        self.bn2   = nn.BatchNorm2d(out_ch)

        #This is the skip connection
        self.skip  = nn.Identity() if (in_ch == out_ch and stride == 1) else \
                     nn.Sequential(nn.Conv2d(in_ch, out_ch, 1, stride=stride, bias=False),
                                   nn.BatchNorm2d(out_ch))
        self.drop_path_rate = drop_path

    def forward(self, x):
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        if self.training and self.drop_path_rate > 0:
            keep = torch.rand(x.size(0), 1, 1, 1, device=x.device) > self.drop_path_rate
            out = out * keep / (1 - self.drop_path_rate)
        return F.relu(out + self.skip(x))

class SimpleCNN(nn.Module):
    def __init__(self, num_classes: int = 100):
        super().__init__()
        self.features = nn.Sequential(
            #Initial conv layer
            nn.Conv2d(3, 64, 3, padding=1, bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),

            #For this part, wanted a way to emulate having more conv layers without affecting
            #the training quality. I tried adding more conv layers here (+ a simple residual block) but it was not
            #really increasing the accuracy.

            #AI assitance was used here for help in this part to structure the residual blocks within the CNN.
            #similar to a resnet style architecture
            ResidualBlock(64, 64,   drop_path=0.05),
            ResidualBlock(64, 128,  stride=2, drop_path=0.05),
            ResidualBlock(128, 128, drop_path=0.1),
            ResidualBlock(128, 256, stride=2, drop_path=0.1),
            ResidualBlock(256, 256, drop_path=0.15),
            ResidualBlock(256, 512, stride=2, drop_path=0.15),
            ResidualBlock(512, 512, drop_path=0.2),
            ResidualBlock(512, 512, drop_path=0.2),
        )

        self.classifier = nn.Sequential(
            #reducing each feature map to one value
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(512, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(inplace=True),
            nn.Dropout(0.5), #regularization to avoid overfitting
            nn.Linear(256, num_classes),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.classifier(self.features(x))


def fit(
    model: nn.Module,
    train_loader: DataLoader,
    val_loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    criterion: nn.Module,
    device: torch.device,
    epochs: int,
    scheduler=None,
) -> Dict[str, list]:
    history = {"train_acc": [], "val_acc": []}
    best_val_acc = -1.0
    best_state = None

    for epoch in range(1, epochs + 1):
        model.train()
        tr_correct, tr_total = 0, 0

        for x, y in tqdm(train_loader, desc=f"train {epoch}/{epochs}", leave=False):
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(x)
            loss = criterion(logits, y)
            loss.backward()
            optimizer.step()
            tr_correct += (logits.argmax(1) == y).sum().item()
            tr_total += y.numel()

        model.eval()
        va_correct, va_total = 0, 0
        with torch.no_grad():
            for x, y in tqdm(val_loader, desc=f"val {epoch}/{epochs}", leave=False):
                x, y = x.to(device), y.to(device)
                logits = model(x)
                va_correct += (logits.argmax(1) == y).sum().item()
                va_total += y.numel()

        tr_acc = tr_correct / max(tr_total, 1)
        va_acc = va_correct / max(va_total, 1)
        history["train_acc"].append(tr_acc)
        history["val_acc"].append(va_acc)
        print(f"Epoch {epoch:03d}/{epochs} | train {tr_acc:.4f} | val {va_acc:.4f}")

        if scheduler is not None:
            scheduler.step()

        if va_acc > best_val_acc:
            best_val_acc = va_acc
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

    if best_state is not None:
        model.load_state_dict(best_state)
    print("Best val acc:", best_val_acc)
    return history


@torch.no_grad()
def eval_clean(model: nn.Module, loader: DataLoader, device: torch.device) -> float:
    model.eval()
    correct, total = 0, 0
    for x, y in loader:
        x, y = x.to(device), y.to(device)
        logits = model(x)
        correct += (logits.argmax(1) == y).sum().item()
        total += y.numel()
    return 100.0 * correct / total


set_seed(SEED)
device = get_device()
print("Device:", device)

!pip install torchinfo

from torch.optim.lr_scheduler import LinearLR, CosineAnnealingLR, SequentialLR
from torchinfo import summary


CFG = {
    #used a batch size of 128
    "batch_size": 128,
    "num_workers": 2,
    #ran for 150 epochs (tried 100-120 epochs earlier)
    "epochs": 150 if not FAST_DEV_RUN else 2,
    #for this configuration and epcohs, I found this lr and weight decay to be optimal
    "lr": 0.1,
    "weight_decay": 5e-4,
}

train_loader, val_loader, test_loader = make_loaders(CFG["batch_size"], CFG["num_workers"])

model = SimpleCNN().to(device)

#using label smoothing to improve the model's generalization
criterion = nn.CrossEntropyLoss(label_smoothing=0.1)

#https://discuss.pytorch.org/t/weight-decay-in-the-optimizers-is-a-bad-idea-especially-with-batchnorm/16994/7
#referenced the above link for the code snippet below
#avoiding adding weight decay to the batch normalization layers
#no_decay contains the parameters for the batch norm layer
decay, no_decay = [], []
for name, param in model.named_parameters():
    if "bn" in name or "bias" in name:
        no_decay.append(param)
    else:
        decay.append(param)

#using the SGD optimizer only for layers other than batch norm
optimizer = torch.optim.SGD([
    {"params": decay, "weight_decay": 5e-4},
    {"params": no_decay, "weight_decay": 0.0}
], lr=CFG["lr"], momentum=0.9, nesterov=True)

#to gradually lower the lr in the later epochs
# After warmup of 15 epcohs using LinearLR, gradually reduce learning rate using cosine annealing
warmup_epochs = 15
scheduler1 = LinearLR(optimizer, start_factor=0.1, end_factor=1.0, total_iters=warmup_epochs)
scheduler2 = CosineAnnealingLR(optimizer, T_max=CFG["epochs"] - warmup_epochs, eta_min=1e-6)
# Combine both schedulers with warmup first, then cosine decay
scheduler = SequentialLR(optimizer, schedulers=[scheduler1, scheduler2], milestones=[warmup_epochs])

history = fit(model, train_loader, val_loader, optimizer, criterion, device, CFG["epochs"], scheduler=scheduler)
test_acc = eval_clean(model, test_loader, device)
print(f"Clean CIFAR-100 test accuracy: {test_acc:.2f}%")

from google.colab import drive
import torch

drive.mount('/content/drive')

torch.save(model.state_dict(),
           "/content/drive/MyDrive/resnet50_cifar100_1.pth")
model = SimpleCNN().to(device)
model.load_state_dict(torch.load("/content/drive/MyDrive/resnet50_cifar100_1.pth"))

#researched online to find ways to improve the accuracy of the model after training
#the TTA model runs inference multiple times using randomly augmented versions
#of the same input image, then averages predictions

class TTAModel(nn.Module):
    def __init__(self, model, n_aug=5):
        super().__init__()
        self.model = model
        # makes n_aug predictions per image and then averages them up
        self.n_aug = n_aug
        self.tta_tfms = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(32, padding=4),
        ])

    def forward(self, x):
        logits = self.model(x)
        for _ in range(self.n_aug - 1):
            x_aug = torch.stack([self.tta_tfms(img) for img in x])
            logits = logits + self.model(x_aug)
        return logits / self.n_aug

model_tta = TTAModel(model, n_aug=6)

val_acc_before = eval_clean(model, val_loader, device)
print(f"Val acc without TTA: {val_acc_before:.2f}%")

#with TTA
model_tta = TTAModel(model, n_aug=6)
model_tta.eval()

val_acc_after = eval_clean(model_tta, val_loader, device)
print(f"Val acc with TTA:    {val_acc_after:.2f}%")

### DO NOT CHANGE THE BELOW, REPLACE WITH YOUR MODEL, THE SUBMISSION FILES NEED TO GO THROUGH THE BELOW PREPROCESSING

from huggingface_hub import snapshot_download

def ensure_ood_files(ood_dir: str) -> None:
    os.makedirs(ood_dir, exist_ok=True)
    print("Downloading OOD files from Hugging Face dataset...")
    snapshot_download(
        repo_id="XThomasBU/ood-test-CS541",
        repo_type="dataset",
        local_dir=ood_dir,
        local_dir_use_symlinks=False,
    )
    print("OOD files ready in", ood_dir)


@torch.no_grad()
def predict_file(model: nn.Module, npy_path: str, severity: int, batch_size: int) -> np.ndarray:
    images = np.load(npy_path, mmap_mode="r")
    start = (severity - 1) * 10000
    end = severity * 10000

    mean = (0.5071, 0.4867, 0.4408)
    std = (0.2675, 0.2565, 0.2761)
    normalize = transforms.Normalize(mean, std)

    preds = []
    model.eval()
    for b0 in tqdm(range(start, end, batch_size), desc=f"{os.path.basename(npy_path)} sev{severity}", leave=False):
        b1 = min(b0 + batch_size, end)
        xb_np = np.array(images[b0:b1], copy=True)
        xb = torch.from_numpy(xb_np).permute(0, 3, 1, 2).float().div(255.0)
        xb = normalize(xb).to(device, non_blocking=True)
        logits = model(xb)
        preds.append(logits.argmax(1).cpu().numpy())
    return np.concatenate(preds, axis=0)


ensure_ood_files(OOD_DIR)

distortion_files = sorted([p for p in os.listdir(OOD_DIR) if p.startswith("distortion") and p.endswith(".npy")])
print("Distortion files found:", len(distortion_files))

rows = []
BATCH = 64 if device.type == "cuda" else 32
for fname in distortion_files:
    dname = os.path.splitext(fname)[0]
    path = os.path.join(OOD_DIR, fname)
    for severity in [1, 2, 3, 4, 5]:
        pred = predict_file(model, path, severity, BATCH)
        for i, y in enumerate(pred.tolist()):
            rows.append((f"{dname}_{severity}_{i}", int(y)))
        print(f"{dname}_{severity} done")

submission = pd.DataFrame(rows, columns=["id", "label"])
submission.to_csv(SUBMISSION_PATH, index=False)
print("Wrote", SUBMISSION_PATH, "rows:", len(submission))