# -*- coding: utf-8 -*-
"""dinov2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pfs_N0BV9TE5ZrN45symnHdi7CEqHr3p

##Name: Chris Mary Benson
##ID: U56085268  
##Email: chris27@bu.edu  

#*This code was run on a Kaggle Notebook (training)

## FINETUNING A PRE-TRAINED TRANSFORMER MODEL ON CIFAR100
Model: https://huggingface.co/facebook/dinov2-small
"""

# Runtime configuration
FAST_DEV_RUN = False  # True = quick smoke test
SEED = 42

import os

IN_COLAB = False
try:
    import google.colab  # type: ignore
    IN_COLAB = False
except Exception:
    IN_COLAB = False

WORK_ROOT = "/content" if IN_COLAB else os.path.abspath("./temp_student")
os.makedirs(WORK_ROOT, exist_ok=True)

DATA_ROOT = os.path.join(WORK_ROOT, "data")
OOD_DIR = os.path.join(WORK_ROOT, "ood-test-CS541")
SUBMISSION_PATH = os.path.join(WORK_ROOT, "ChrisMaryBenson_part2_4.csv")

print("IN_COLAB:", IN_COLAB)
print("WORK_ROOT:", WORK_ROOT)
print("DATA_ROOT:", DATA_ROOT)
print("OOD_DIR:", OOD_DIR)
print("SUBMISSION_PATH:", SUBMISSION_PATH)

# Install required packages (safe to re-run)
import importlib.util
import subprocess
import sys

required = ["torch", "torchvision", "tqdm", "numpy", "pandas", "matplotlib", "huggingface_hub"]
missing = [p for p in required if importlib.util.find_spec(p) is None]
if missing:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-U", *missing])

print("Environment ready")

pip install timm

from torchvision import models

from timm.data.mixup import Mixup

import timm
import torch

#getting the dinov2 model
model = timm.create_model(
    'vit_small_patch14_dinov2.lvd142m',
    pretrained=True,
    num_classes=100,
    img_size=224
)

model = model.to(device)

#adding mixup
mixup_fn = Mixup(
    mixup_alpha=0.8,
    cutmix_alpha=1.0,
    prob=0.9,
    label_smoothing=0.1,
    num_classes=100
)

print(model.__class__.__name__)
print(next(model.parameters()).device)

import os
import random
from typing import Dict, Optional, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.transforms import v2
from tqdm import tqdm

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def get_device() -> torch.device:
    if torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


def accuracy_top1(logits: torch.Tensor, targets: torch.Tensor) -> float:
    return (logits.argmax(dim=1) == targets).float().mean().item()

def make_loaders(batch_size: int, num_workers: int) -> Tuple[DataLoader, DataLoader, DataLoader]:
    mean = (0.5071, 0.4867, 0.4408) ### DO NOT CHANGE THIS
    std = (0.2675, 0.2565, 0.2761) ### DO NOT CHANGE THIS

    train_tfms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomCrop(224, padding=28),
    transforms.RandomHorizontalFlip(),
    #new augmentation technique
    transforms.RandomRotation(7),
    #new data augmentation technique
    transforms.RandomAffine(
        degrees=10,
        translate=(0.1, 0.1),
        scale=(0.9, 1.1),
        shear=5
    ),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.RandomGrayscale(p=0.1),
    transforms.AugMix(),
    transforms.RandomApply([transforms.GaussianBlur(kernel_size=3, sigma=(0.1, 2.0))], p=0.3),
    transforms.ToTensor(),
    transforms.RandomErasing(p=0.25, scale=(0.02, 0.2)),
    transforms.Normalize(mean, std),
])

    eval_tfms = transforms.Compose([transforms.Resize((224, 224)), transforms.ToTensor(), transforms.Normalize(mean, std)])

    train_full = datasets.CIFAR100(root=DATA_ROOT, train=True, download=True, transform=train_tfms)
    test_ds = datasets.CIFAR100(root=DATA_ROOT, train=False, download=True, transform=eval_tfms)

    n = len(train_full)
    n_train = int(0.8 * n)
    n_val = n - n_train
    g = torch.Generator().manual_seed(SEED)
    train_ds, val_ds = torch.utils.data.random_split(train_full, [n_train, n_val], generator=g)

    pin = torch.cuda.is_available()
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=pin)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=pin)
    test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=pin)
    return train_loader, val_loader, test_loader

def fit(
    model: nn.Module,
    train_loader: DataLoader,
    val_loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    criterion: nn.Module,
    device: torch.device,
    epochs: int,
    #adding scheduler
    scheduler=None,
) -> Dict[str, list]:
    history = {"train_acc": [], "val_acc": []}
    best_val_acc = -1.0
    best_state = None

    patience = 15
    epochs_no_improve = 0

    for epoch in range(1, epochs + 1):

        model.train()
        tr_correct, tr_total = 0, 0
        for x, y in tqdm(train_loader, desc=f"train {epoch}/{epochs}", leave=False):
            x, y = x.to(device), y.to(device)
            x, y_mixed = mixup_fn(x, y)
            optimizer.zero_grad(set_to_none=True)
            logits = model(x)
            loss = criterion(logits, y_mixed)
            loss.backward()
            optimizer.step()
            tr_correct += (logits.argmax(1) == y).sum().item()
            tr_total += y.numel()

        model.eval()
        va_correct, va_total = 0, 0
        with torch.no_grad():
            for x, y in tqdm(val_loader, desc=f"val {epoch}/{epochs}", leave=False):
                x, y = x.to(device), y.to(device)
                logits = model(x)
                va_correct += (logits.argmax(1) == y).sum().item()
                va_total += y.numel()

        tr_acc = tr_correct / max(tr_total, 1)
        va_acc = va_correct / max(va_total, 1)
        history["train_acc"].append(tr_acc)
        history["val_acc"].append(va_acc)
        print(f"Epoch {epoch:03d}/{epochs} | train {tr_acc:.4f} | val {va_acc:.4f}")

        if scheduler is not None:
           scheduler.step()

        if va_acc > best_val_acc:
            best_val_acc = va_acc
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

        #adding early stopping with patience -
        # if va_acc > best_val_acc:
        #     best_val_acc = va_acc
        #     epochs_no_improve = 0
        #     best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        # else:
        #     epochs_no_improve += 1
        #     if epochs_no_improve >= patience:
        #         print(f"Early stopping at epoch {epoch}")
        #         break

    if best_state is not None:
        model.load_state_dict(best_state)
    print("Best val acc:", best_val_acc)
    return history


@torch.no_grad()
def eval_clean(model: nn.Module, loader: DataLoader, device: torch.device) -> float:
    model.eval()
    correct, total = 0, 0
    for x, y in loader:
        x, y = x.to(device), y.to(device)
        logits = model(x)
        correct += (logits.argmax(1) == y).sum().item()
        total += y.numel()
    return 100.0 * correct / total


set_seed(SEED)
device = get_device()
print("Device:", device)

from torch.optim.lr_scheduler import LinearLR, CosineAnnealingLR, SequentialLR
from timm.loss import SoftTargetCrossEntropy

CFG = {
    "batch_size": 64,
    "num_workers": 2,
    "epochs": 50,
    "weight_decay": 0.05,
}

train_loader, val_loader, test_loader = make_loaders(CFG["batch_size"], CFG["num_workers"])
#using softtargetcrossentropy since mixup is used
criterion = SoftTargetCrossEntropy()

#unfreezing only the classification head for 5 epochs
for name, param in model.named_parameters():
    if 'head' not in name:
        param.requires_grad = False

optimizer = torch.optim.AdamW(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=3e-4,
    weight_decay=CFG["weight_decay"]
)

print("── Step 1: Training head only ──")
history_lp = fit(model, train_loader, val_loader, optimizer, criterion, device, epochs=5)

#after the previous 5 epochs, we unfreeze all the layers for full fine tuning of the transformer model
for param in model.parameters():
    param.requires_grad = True

#AI assisstance used here for help with optimal hyperparameters as well as structuring the optimizer with the parts

#We assign different learning rates in the optimizer for different parts of the model
optimizer = torch.optim.AdamW([
    #this is the classification head, we assign a higher lr
    {'params': model.head.parameters(),'lr': 3e-4},
    #the backbone of the model, we assign a lower lr
    {'params': model.blocks.parameters(),'lr': 3e-5},
    #and even lower lr because its an early feature extractor
    {'params': model.patch_embed.parameters(),'lr': 1e-5},
], weight_decay=CFG["weight_decay"])

#same scheduler technique used for part 2
warmup_epochs = 5
scheduler1 = LinearLR(optimizer, start_factor=0.1, end_factor=1.0, total_iters=warmup_epochs)
scheduler2 = CosineAnnealingLR(optimizer, T_max=45 - warmup_epochs, eta_min=1e-6)
scheduler  = SequentialLR(optimizer, schedulers=[scheduler1, scheduler2], milestones=[warmup_epochs])

print("── Step 2: Full finetuning ──")
history_ft = fit(model, train_loader, val_loader, optimizer, criterion, device, epochs=45, scheduler=scheduler)

test_acc = eval_clean(model, test_loader, device)
print(f"Clean CIFAR-100 test accuracy: {test_acc:.2f}%")

torch.save(model.state_dict(), "/kaggle/working/dinov2_part3.pth")

# Optional quick plot of train/val accuracy
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.plot(history["train_acc"], label="train")
plt.plot(history["val_acc"], label="val")
plt.title("Baseline Accuracy")
plt.xlabel("epoch")
plt.ylabel("accuracy")
plt.legend()
plt.show()

import torch.nn.functional as F

#AI assistance used here with the below code
#using TTA model to get better predictions
class TTAModel(nn.Module):
    def __init__(self, model):
        super().__init__()
        self.model = model
        self.resize = transforms.Resize((224, 224))

    @torch.no_grad()
    def forward(self, x):
        x = self.resize(x)
        probs = F.softmax(self.model(x), dim=1) * 2.0

        #Horizontal Flip
        x_flip = transforms.functional.hflip(x)
        probs += F.softmax(self.model(x_flip), dim=1)

        #Center Crop + Resize
        x_crop = transforms.CenterCrop(200)(x)
        x_crop = F.interpolate(x_crop, size=(224, 224), mode='bicubic', align_corners=False)
        probs += F.softmax(self.model(x_crop), dim=1)

        return probs / 4.0

val_acc_before = eval_clean(model, val_loader, device)
print(f"Val acc without TTA: {val_acc_before:.2f}%")

model_tta = TTAModel(model)
model_tta.eval()

val_acc_after = eval_clean(model_tta, val_loader, device)
print(f"Val acc with TTA:    {val_acc_after:.2f}%")

"""**CODE FOR RETREIVING THE SAVED MODEL**"""

from torch.optim.lr_scheduler import LinearLR, CosineAnnealingLR, SequentialLR
from timm.loss import SoftTargetCrossEntropy

CFG = {
    "batch_size": 64,
    "num_workers": 2,
    "epochs": 50,
    "weight_decay": 0.05,
}

train_loader, val_loader, test_loader = make_loaders(CFG["batch_size"], CFG["num_workers"])
criterion = SoftTargetCrossEntropy()

from google.colab import drive
import torch
drive.mount('/content/drive')

"""**INFERENCE ON THE TRAINED MODEL**"""

from torchvision import models
import timm

model = timm.create_model('vit_small_patch14_dinov2', pretrained=False, num_classes=100, img_size=224)
model.load_state_dict(torch.load('/content/drive/MyDrive/dinov2_part3.pth'))
model = model.to(device)

"""**TOP 3 BEST PERFORMING CLASSES**"""

#AI assistance used here (alongside my code)
import torch
from collections import defaultdict

model.eval()

#correct predictions per class
class_correct = defaultdict(int)
#total number of images per class that were predicted correct
class_total = defaultdict(int)

with torch.no_grad():
    #did inference on both val and test loaders
    for images, labels in val_loader:
        images, labels = images.to(device), labels.to(device)

        #get the model predictions which is the logits
        outputs = model(images)
        #and convert to the class indice
        preds = torch.argmax(outputs, dim=1)

        for label, pred in zip(labels, preds):
            label = label.item()
            pred = pred.item()

            class_total[label] += 1
            if label == pred:
                class_correct[label] += 1

#compute accuracy for each class
class_acc = {
    cls: class_correct[cls] / class_total[cls]
    for cls in class_total
}

best_classes = sorted(class_acc.items(), key=lambda x: x[1], reverse=True)[:3]

print("Top 3 BEST-performing classes:")
for cls, acc in best_classes:
    print(f"Class {cls}: Accuracy = {acc:.4f}, Samples = {class_total[cls]}")

best_class_ids = [cls for cls, _ in best_classes]

best_class_images = {cls: [] for cls in best_class_ids}

model.eval()
with torch.no_grad():
    for images, labels in val_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        preds = torch.argmax(outputs, dim=1)

        for i in range(len(images)):
            true = labels[i].item()
            pred = preds[i].item()

            if true in best_class_ids and true == pred:
                if len(best_class_images[true]) < 3:
                    best_class_images[true].append(images[i].cpu())

# On clean test dataset
import matplotlib.pyplot as plt

mean = [0.5071, 0.4867, 0.4408]
std = [0.2675, 0.2565, 0.2761]

for cls in best_class_ids:
    print(f"\nClass {cls} (Best Performing)")

    for img in best_class_images[cls]:
        img_np = img.permute(1, 2, 0).numpy()

        img_np = img_np * std + mean
        img_np = img_np.clip(0, 1)

        plt.imshow(img_np)
        plt.title(f"Class {cls}")
        plt.axis('off')
        plt.show()

# On validation set (with distortions applied from the data augmentations)
import matplotlib.pyplot as plt

mean = [0.5071, 0.4867, 0.4408]
std = [0.2675, 0.2565, 0.2761]

for cls in best_class_ids:
    print(f"\nClass {cls} (Best Performing)")

    for img in best_class_images[cls]:
        img_np = img.permute(1, 2, 0).numpy()

        img_np = img_np * std + mean
        img_np = img_np.clip(0, 1)

        plt.imshow(img_np)
        plt.title(f"Class {cls}")
        plt.axis('off')
        plt.show()

"""**TOP 3 WORST PERFORMING CLASSES**"""

#Top 3 worst performing
worst_classes = sorted(class_acc.items(), key=lambda x: x[1])[:3]
worst_class_ids = [cls for cls, _ in worst_classes]
worst_class_correct = {cls: [] for cls in worst_class_ids}
worst_class_wrong = {cls: [] for cls in worst_class_ids}

model.eval()
with torch.no_grad():
    for images, labels in val_loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        preds = torch.argmax(outputs, dim=1)

        for i in range(len(images)):
            true = labels[i].item()
            pred = preds[i].item()

            if true in worst_class_ids:
                # store a few correct examples
                if pred == true and len(worst_class_correct[true]) < 3:
                    worst_class_correct[true].append(images[i].cpu())

                # store a few wrong examples
                if pred != true and len(worst_class_wrong[true]) < 3:
                    worst_class_wrong[true].append((images[i].cpu(), pred))

#For the test images
import matplotlib.pyplot as plt

mean = [0.5071, 0.4867, 0.4408]
std = [0.2675, 0.2565, 0.2761]

for cls in worst_class_ids:
    print(f"\n=== Class {cls} (Worst Performing) ===")

    # ---- Correct predictions ----
    print("Correct predictions:")
    for img in worst_class_correct[cls]:
        img_np = img.permute(1, 2, 0).numpy()
        img_np = img_np * std + mean
        img_np = img_np.clip(0, 1)

        plt.imshow(img_np)
        plt.title(f"Class {cls} (Correct)")
        plt.axis('off')
        plt.show()

    # ---- Incorrect predictions ----
    print("Incorrect predictions:")
    for img, pred in worst_class_wrong[cls]:
        img_np = img.permute(1, 2, 0).numpy()
        img_np = img_np * std + mean
        img_np = img_np.clip(0, 1)

        plt.imshow(img_np)
        plt.title(f"True: {cls}, Pred: {pred}")
        plt.axis('off')
        plt.show()

#For the validation images

import matplotlib.pyplot as plt

mean = [0.5071, 0.4867, 0.4408]
std = [0.2675, 0.2565, 0.2761]

for cls in worst_class_ids:
    print(f"\n=== Class {cls} (Worst Performing) ===")

    # ---- Correct predictions ----
    print("Correct predictions:")
    for img in worst_class_correct[cls]:
        img_np = img.permute(1, 2, 0).numpy()
        img_np = img_np * std + mean
        img_np = img_np.clip(0, 1)

        plt.imshow(img_np)
        plt.title(f"Class {cls} (Correct)")
        plt.axis('off')
        plt.show()

    # ---- Incorrect predictions ----
    print("Incorrect predictions:")
    for img, pred in worst_class_wrong[cls]:
        img_np = img.permute(1, 2, 0).numpy()
        img_np = img_np * std + mean
        img_np = img_np.clip(0, 1)

        plt.imshow(img_np)
        plt.title(f"True: {cls}, Pred: {pred}")
        plt.axis('off')
        plt.show()

result = model.load_state_dict(torch.load('/kaggle/input/datasets/chris272002/dino-v3/dinov2_part3.pth'))
print(result)

#used this when testing without the TTA Model
#to resize the 32x32 images to 224x224
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.resize = transforms.Resize((224, 224))
        self.model = model

    def forward(self, x):
        x = self.resize(x)
        return self.model(x)

trained_model = MyModel().to(device)

print("Done")

### DO NOT CHANGE THE BELOW, REPLACE WITH YOUR MODEL, THE SUBMISSION FILES NEED TO GO THROUGH THE BELOW PREPROCESSING

from huggingface_hub import snapshot_download

def ensure_ood_files(ood_dir: str) -> None:
    os.makedirs(ood_dir, exist_ok=True)
    print("Downloading OOD files from Hugging Face dataset...")
    snapshot_download(
        repo_id="XThomasBU/ood-test-CS541",
        repo_type="dataset",
        local_dir=ood_dir,
        local_dir_use_symlinks=False,
    )
    print("OOD files ready in", ood_dir)


@torch.no_grad()
def predict_file(model: nn.Module, npy_path: str, severity: int, batch_size: int) -> np.ndarray:
    images = np.load(npy_path, mmap_mode="r")
    start = (severity - 1) * 10000
    end = severity * 10000

    mean = (0.5071, 0.4867, 0.4408)
    std = (0.2675, 0.2565, 0.2761)
    normalize = transforms.Normalize(mean, std)

    preds = []
    model.eval()
    for b0 in tqdm(range(start, end, batch_size), desc=f"{os.path.basename(npy_path)} sev{severity}", leave=False):
        b1 = min(b0 + batch_size, end)
        xb_np = np.array(images[b0:b1], copy=True)
        xb = torch.from_numpy(xb_np).permute(0, 3, 1, 2).float().div(255.0)
        xb = normalize(xb).to(device, non_blocking=True)
        logits = model(xb)
        preds.append(logits.argmax(1).cpu().numpy())
    return np.concatenate(preds, axis=0)


ensure_ood_files(OOD_DIR)

distortion_files = sorted([p for p in os.listdir(OOD_DIR) if p.startswith("distortion") and p.endswith(".npy")])
print("Distortion files found:", len(distortion_files))

rows = []
BATCH = 64 if device.type == "cuda" else 32
for fname in distortion_files:
    dname = os.path.splitext(fname)[0]
    path = os.path.join(OOD_DIR, fname)
    for severity in [1, 2, 3, 4, 5]:
        pred = predict_file(model_tta, path, severity, BATCH)
        for i, y in enumerate(pred.tolist()):
            rows.append((f"{dname}_{severity}_{i}", int(y)))
        print(f"{dname}_{severity} done")

submission = pd.DataFrame(rows, columns=["id", "label"])
submission.to_csv(SUBMISSION_PATH, index=False)
print("Wrote", SUBMISSION_PATH, "rows:", len(submission))