# -*- coding: utf-8 -*-
"""Resnet50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NEb023m_hHK3nNKhbBjq4-YL4ycTpMZu

##Name: Chris Mary Benson
##ID: U56085268  
##Email: chris27@bu.edu  

#*This code was run on a Kaggle Notebook (training)
---

## FINETUNING A PRE-TRAINED CNN MODEL ON CIFAR100
"""

# Runtime configuration
FAST_DEV_RUN = False  # True = quick smoke test
SEED = 42

import os

IN_COLAB = False
try:
    import google.colab  # type: ignore
    IN_COLAB = True
except Exception:
    IN_COLAB = False

WORK_ROOT = "/content" if IN_COLAB else os.path.abspath("./temp_student")
os.makedirs(WORK_ROOT, exist_ok=True)

DATA_ROOT = os.path.join(WORK_ROOT, "data")
OOD_DIR = os.path.join(WORK_ROOT, "ood-test-CS541")
SUBMISSION_PATH = os.path.join(WORK_ROOT, "ChrisMaryBenson_part2_3.csv")

print("IN_COLAB:", IN_COLAB)
print("WORK_ROOT:", WORK_ROOT)
print("DATA_ROOT:", DATA_ROOT)
print("OOD_DIR:", OOD_DIR)
print("SUBMISSION_PATH:", SUBMISSION_PATH)

# Install required packages (safe to re-run)
import importlib.util
import subprocess
import sys

required = ["torch", "torchvision", "tqdm", "numpy", "pandas", "matplotlib", "huggingface_hub"]
missing = [p for p in required if importlib.util.find_spec(p) is None]
if missing:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-U", *missing])

print("Environment ready")

import os

os.makedirs("/tmp/cifar100/cifar-100-python", exist_ok=True)

for f in ["train", "test", "meta"]:
    src = f"/kaggle/input/datasets/chris272002/cifar-100/{f}"
    dst = f"/tmp/cifar100/cifar-100-python/{f}"
    if os.path.islink(dst) or os.path.exists(dst):
        continue
    try:
        os.symlink(src, dst)
    except FileExistsError:
        pass

DATA_ROOT = "/tmp/cifar100"

from torchvision import models
import torch.nn as nn
from torchvision.models import ResNet50_Weights

#using the pre trained resnet50 model
model = models.resnet50(weights=ResNet50_Weights.IMAGENET1K_V1)

#replacing the 7x7 conv layer of resnet to 3x3 to match the input size of CIFAR 100 images
model.conv1 = nn.Conv2d(3, 64, 3, padding=1, bias=False)

#Since CIFAR images are small, we want to preserve the spatial context
#hence we remove the maxpool layer

#AI assistance used for this
model.maxpool = nn.Identity()


num_features = model.fc.in_features
#replacing the classifier head with the below
#to match 100 classes of CIFAR instead of 1000
model.fc = nn.Sequential(
    nn.Dropout(0.5),
    nn.Linear(num_features, 512),
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(512, 100)
)

import os
import random
from typing import Dict, Optional, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.transforms import v2
from tqdm import tqdm

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def get_device() -> torch.device:
    if torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


def accuracy_top1(logits: torch.Tensor, targets: torch.Tensor) -> float:
    return (logits.argmax(dim=1) == targets).float().mean().item()

def make_loaders(batch_size: int, num_workers: int) -> Tuple[DataLoader, DataLoader, DataLoader]:
    mean = (0.5071, 0.4867, 0.4408) ### DO NOT CHANGE THIS
    std = (0.2675, 0.2565, 0.2761) ### DO NOT CHANGE THIS

    #adding data augmentation
    train_tfms = transforms.Compose([
         transforms.RandomHorizontalFlip(),
         transforms.RandomCrop(32,padding = 4),
         transforms.ColorJitter(brightness=0.2, contrast=0.2),
         transforms.RandomGrayscale(p=0.1),
         transforms.RandomApply([transforms.GaussianBlur(kernel_size=3, sigma=(0.1, 1.0))], p=0.2),
         transforms.AugMix(severity=3, mixture_width=3),
         transforms.RandAugment(num_ops=3, magnitude=15),
         transforms.ToTensor(),
         transforms.Normalize(mean, std),
         transforms.RandomErasing(p=0.3, scale=(0.02, 0.2))
       ])

    eval_tfms = transforms.Compose([transforms.ToTensor(), transforms.Normalize(mean, std)])

    train_full = datasets.CIFAR100(root=DATA_ROOT, train=True, download=True, transform=train_tfms)
    test_ds = datasets.CIFAR100(root=DATA_ROOT, train=False, download=True, transform=eval_tfms)

    n = len(train_full)
    n_train = int(0.8 * n)
    n_val = n - n_train
    g = torch.Generator().manual_seed(SEED)
    train_ds, val_ds = torch.utils.data.random_split(train_full, [n_train, n_val], generator=g)

    pin = torch.cuda.is_available()
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=pin)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=pin)
    test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=pin)
    return train_loader, val_loader, test_loader

def fit(
    model: nn.Module,
    train_loader: DataLoader,
    val_loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    criterion: nn.Module,
    device: torch.device,
    epochs: int,
    #adding scheduler
    scheduler=None,
) -> Dict[str, list]:
    history = {"train_acc": [], "val_acc": []}
    best_val_acc = -1.0
    best_state = None

    for epoch in range(1, epochs + 1):

        model.train()
        tr_correct, tr_total = 0, 0
        for x, y in tqdm(train_loader, desc=f"train {epoch}/{epochs}", leave=False):
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(x)
            loss = criterion(logits, y)
            loss.backward()
            optimizer.step()
            tr_correct += (logits.argmax(1) == y).sum().item()
            tr_total += y.numel()

        model.eval()
        va_correct, va_total = 0, 0
        with torch.no_grad():
            for x, y in tqdm(val_loader, desc=f"val {epoch}/{epochs}", leave=False):
                x, y = x.to(device), y.to(device)
                logits = model(x)
                va_correct += (logits.argmax(1) == y).sum().item()
                va_total += y.numel()

        tr_acc = tr_correct / max(tr_total, 1)
        va_acc = va_correct / max(va_total, 1)
        history["train_acc"].append(tr_acc)
        history["val_acc"].append(va_acc)
        print(f"Epoch {epoch:03d}/{epochs} | train {tr_acc:.4f} | val {va_acc:.4f}")

        if scheduler is not None:
           scheduler.step()

        if va_acc > best_val_acc:
            best_val_acc = va_acc
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

    if best_state is not None:
        model.load_state_dict(best_state)
    print("Best val acc:", best_val_acc)
    return history


@torch.no_grad()
def eval_clean(model: nn.Module, loader: DataLoader, device: torch.device) -> float:
    model.eval()
    correct, total = 0, 0
    for x, y in loader:
        x, y = x.to(device), y.to(device)
        logits = model(x)
        correct += (logits.argmax(1) == y).sum().item()
        total += y.numel()
    return 100.0 * correct / total


set_seed(SEED)
device = get_device()
print("Device:", device)

# Baseline training config
from torch.optim.lr_scheduler import StepLR

CFG = {
    "batch_size": 64,
    "num_workers": 0 if IN_COLAB else 2,
    #trying with 100 epochs
    "epochs": 100 if not FAST_DEV_RUN else 2,
    "lr": 1e-3,
    #increasing weight decay
    "weight_decay": 5e-4,
}

train_loader, val_loader, test_loader = make_loaders(CFG["batch_size"], CFG["num_workers"])

#Increasing label smoothing to 0.2
criterion = nn.CrossEntropyLoss(label_smoothing=0.2)
model = model.to(device)

# optimizer = torch.optim.AdamW(model.parameters(), lr=CFG["lr"], weight_decay=CFG["weight_decay"])

#trying with SGD
optimizer = torch.optim.SGD(
    model.parameters(),
    lr = CFG["lr"],
    momentum=0.9,
    weight_decay = CFG["weight_decay"],
    nesterov=True
)

#scheduler = StepLR(optimizer, step_size=30, gamma=0.1)

#added scheduler to decay the learning rate after the accuracy plateaus
#scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=10, min_lr=1e-6, factor=0.5)

#Final scheduler used was CosinneAnnealing
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=100)


history = fit(model, train_loader, val_loader, optimizer, criterion, device, CFG["epochs"], scheduler = scheduler)
test_acc = eval_clean(model, test_loader, device)
print(f"Clean CIFAR-100 test accuracy: {test_acc:.2f}%")

torch.save(model.state_dict(), "/kaggle/working/resnet50_cifar100.pth")

# Optional quick plot of train/val accuracy
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.plot(history["train_acc"], label="train")
plt.plot(history["val_acc"], label="val")
plt.title("Baseline Accuracy")
plt.xlabel("epoch")
plt.ylabel("accuracy")
plt.legend()
plt.show()

### DO NOT CHANGE THE BELOW, REPLACE WITH YOUR MODEL, THE SUBMISSION FILES NEED TO GO THROUGH THE BELOW PREPROCESSING

from huggingface_hub import snapshot_download

def ensure_ood_files(ood_dir: str) -> None:
    os.makedirs(ood_dir, exist_ok=True)
    print("Downloading OOD files from Hugging Face dataset...")
    snapshot_download(
        repo_id="XThomasBU/ood-test-CS541",
        repo_type="dataset",
        local_dir=ood_dir,
        local_dir_use_symlinks=False,
    )
    print("OOD files ready in", ood_dir)


@torch.no_grad()
def predict_file(model: nn.Module, npy_path: str, severity: int, batch_size: int) -> np.ndarray:
    images = np.load(npy_path, mmap_mode="r")
    start = (severity - 1) * 10000
    end = severity * 10000

    mean = (0.5071, 0.4867, 0.4408)
    std = (0.2675, 0.2565, 0.2761)
    normalize = transforms.Normalize(mean, std)

    preds = []
    model.eval()
    for b0 in tqdm(range(start, end, batch_size), desc=f"{os.path.basename(npy_path)} sev{severity}", leave=False):
        b1 = min(b0 + batch_size, end)
        xb_np = np.array(images[b0:b1], copy=True)
        xb = torch.from_numpy(xb_np).permute(0, 3, 1, 2).float().div(255.0)
        xb = normalize(xb).to(device, non_blocking=True)
        logits = model(xb)
        preds.append(logits.argmax(1).cpu().numpy())
    return np.concatenate(preds, axis=0)


ensure_ood_files(OOD_DIR)

distortion_files = sorted([p for p in os.listdir(OOD_DIR) if p.startswith("distortion") and p.endswith(".npy")])
print("Distortion files found:", len(distortion_files))

rows = []
BATCH = 64 if device.type == "cuda" else 32
for fname in distortion_files:
    dname = os.path.splitext(fname)[0]
    path = os.path.join(OOD_DIR, fname)
    for severity in [1, 2, 3, 4, 5]:
        pred = predict_file(model, path, severity, BATCH)
        for i, y in enumerate(pred.tolist()):
            rows.append((f"{dname}_{severity}_{i}", int(y)))
        print(f"{dname}_{severity} done")

submission = pd.DataFrame(rows, columns=["id", "label"])
submission.to_csv(SUBMISSION_PATH, index=False)
print("Wrote", SUBMISSION_PATH, "rows:", len(submission))